## Automatically sync fork with upstream
version: "1"
rules:
  - base: IDEAS
    upstream: carpentries:main
    mergeMethod: squash
    mergeUnstable: false
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
